sudo: false

services:
  - docker

script:
  - docker build -t redtankd/base base/
  - docker run --rm redtankd/base fish --version
  - docker run --rm redtankd/base git --version
  - docker run --rm redtankd/base vim --version
  - docker build -t redtankd/rust --build-arg RUSTUP_DIST_SERVER=$RUSTUP_DIST_SERVER rust/
  - docker run --rm redtankd/rust kcov --version
  - docker run --rm redtankd/rust fish -c "rustup run stable cargo --version"
  - docker run --rm redtankd/rust fish -c "rustup run nightly cargo --version"
  - docker run --rm redtankd/rust fish -c "rustup run stable rustc --version"
  - docker run --rm redtankd/rust fish -c "rustup run nightly rustc --version"
  - docker run --rm redtankd/rust fish -c "cargo kcov --version"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push redtankd/rust;
    fi