# Partner Queue Solution, which can be used completely for free.
# https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution
os: linux

arch:
  - arm64

language: rust

rust:
  - nightly

services:
  - docker

addons:
  apt:
    packages:
      - musl-tools

before_script:
  - rustup target add x86_64-unknown-linux-musl --toolchain nightly
  - mkdir .cargo
  - echo -e "[target.x86_64-unknown-linux-musl]\nlinker = \"musl-gcc\"" > .cargo/config

script:
  - cd $TRAVIS_BUILD_DIR/
  - TARGET_CC=musl-gcc cargo +nightly build --target x86_64-unknown-linux-musl
  - docker-compose build
  - docker-compose up -d
  - sleep 30
  - test "200" -eq $(curl --write-out %{http_code} --silent --output /dev/null http://localhost:8000/hello/John/58)
  - docker-compose down

after_success:
  - cd $TRAVIS_BUILD_DIR
  # if images changed, push new images to hub.docker.com
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      if [ ! -z "`git diff --shortstat HEAD^ HEAD -- images/`" ]; then 
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        images/cp-images.sh images/images.properties
      fi
    fi
