sudo: false

language: rust

rust:
  - nightly

services:
  - docker

addons:
  apt:
    packages:
      - musl-tools

before_script:
  - rustup target add x86_64-unknown-linux-musl --toolchain nightly
  - mkdir .cargo
  - echo -e "[target.x86_64-unknown-linux-musl]\nlinker = \"musl-gcc\"" > .cargo/config

script:
  - cd $TRAVIS_BUILD_DIR/docker/base
  # Path outside the build context is forbidden, so the context path is not the path of Dockerfile.
  - docker build -t redtankd/ubuntu-base -f ubuntu/Dockerfile .
  - docker run --rm redtankd/ubuntu-base fish --version
  - docker run --rm redtankd/ubuntu-base git --version
  - docker run --rm redtankd/ubuntu-base vim --version
  - docker build -t redtankd/alpine-base -f alpine/Dockerfile .
  - docker run --rm redtankd/alpine-base fish --version
  - docker run --rm redtankd/alpine-base git --version
  - docker run --rm redtankd/alpine-base vim --version

  - cd $TRAVIS_BUILD_DIR/docker/rust
  - docker build -t redtankd/ubuntu-rust -f ubuntu/Dockerfile --build-arg RUSTUP_DIST_SERVER=$RUSTUP_DIST_SERVER --build-arg SOURCE_CRATES_IO=$SOURCE_CRATES_IO .
  - docker run --rm redtankd/ubuntu-rust fish -c "rustup run stable cargo --version"
  - docker run --rm redtankd/ubuntu-rust fish -c "rustup run nightly cargo --version"
  - docker run --rm redtankd/ubuntu-rust fish -c "rustup run stable rustc --version"
  - docker run --rm redtankd/ubuntu-rust fish -c "rustup run nightly rustc --version"

  - cd $TRAVIS_BUILD_DIR/
  - TARGET_CC=musl-gcc cargo +nightly build --target x86_64-unknown-linux-musl
  - docker-compose build
  - docker-compose up -d
  - sleep 30
  - test "200" -eq $(curl --write-out %{http_code} --silent --output /dev/null http://localhost:8000/hello/John/58)
  - docker-compose down

after_success:
  - cd $TRAVIS_BUILD_DIR
  # if images changed, push new images to hub.docker.com
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      if [ ! -z "`git diff --shortstat HEAD^ HEAD -- images/`" ]; then 
        images/cp-images.sh images/images.properties
      fi
    fi
      if [ ! -z "`git diff --shortstat HEAD^ HEAD -- docker/rust/`" ]; then 
        docker push redtankd/ubuntu-rust
      fi
    fi
