[package]
name = "hello-service"
version = "0.1.0"
authors = ["redtankd <redtankd@qq.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
hostname = "0.1"
reqwest = { version = "0.9.5", default-features = false }
lazy_static = "1.2.0"
